// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: src/proto/drawing.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "game";

export interface DrawingData {
  type: number;
  isLineEnd: boolean;
  coordinates: number[];
  /** RGBA */
  color: number[];
  lineWidth: number;
}

function createBaseDrawingData(): DrawingData {
  return { type: 0, isLineEnd: false, coordinates: [], color: [], lineWidth: 0 };
}

export const DrawingData: MessageFns<DrawingData> = {
  encode(message: DrawingData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.isLineEnd !== false) {
      writer.uint32(16).bool(message.isLineEnd);
    }
    writer.uint32(26).fork();
    for (const v of message.coordinates) {
      writer.int32(v);
    }
    writer.join();
    writer.uint32(34).fork();
    for (const v of message.color) {
      writer.float(v);
    }
    writer.join();
    if (message.lineWidth !== 0) {
      writer.uint32(40).int32(message.lineWidth);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DrawingData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDrawingData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isLineEnd = reader.bool();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.coordinates.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.coordinates.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag === 37) {
            message.color.push(reader.float());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.color.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lineWidth = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DrawingData {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      isLineEnd: isSet(object.isLineEnd) ? globalThis.Boolean(object.isLineEnd) : false,
      coordinates: globalThis.Array.isArray(object?.coordinates)
        ? object.coordinates.map((e: any) => globalThis.Number(e))
        : [],
      color: globalThis.Array.isArray(object?.color) ? object.color.map((e: any) => globalThis.Number(e)) : [],
      lineWidth: isSet(object.lineWidth) ? globalThis.Number(object.lineWidth) : 0,
    };
  },

  toJSON(message: DrawingData): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.isLineEnd !== false) {
      obj.isLineEnd = message.isLineEnd;
    }
    if (message.coordinates?.length) {
      obj.coordinates = message.coordinates.map((e) => Math.round(e));
    }
    if (message.color?.length) {
      obj.color = message.color;
    }
    if (message.lineWidth !== 0) {
      obj.lineWidth = Math.round(message.lineWidth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DrawingData>, I>>(base?: I): DrawingData {
    return DrawingData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DrawingData>, I>>(object: I): DrawingData {
    const message = createBaseDrawingData();
    message.type = object.type ?? 0;
    message.isLineEnd = object.isLineEnd ?? false;
    message.coordinates = object.coordinates?.map((e) => e) || [];
    message.color = object.color?.map((e) => e) || [];
    message.lineWidth = object.lineWidth ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
