// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: src/proto/serialization.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "game";

export interface Event {
  type: number;
  data: string;
}

export interface Message {
  from: string;
  content: string;
}

/** NEW: Single drawing path with Fabric.js data */
export interface DrawingPath {
  /** SVG path data (d attribute) */
  pathData: string;
  /** Color */
  stroke: string;
  /** Line width */
  strokeWidth: number;
  /** Line cap style */
  strokeLineCap: string;
  /** Line join style */
  strokeLineJoin: string;
}

/** NEW: Clear canvas command */
export interface ClearCanvas {
  clear: boolean;
}

export interface WordChoice {
  wordIndex: number;
}

export interface TurnSummary {
  usernames: string[];
  scores: number[];
}

function createBaseEvent(): Event {
  return { type: 0, data: "" };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Event {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      data: isSet(object.data) ? globalThis.String(object.data) : "",
    };
  },

  toJSON(message: Event): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Event>, I>>(base?: I): Event {
    return Event.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Event>, I>>(object: I): Event {
    const message = createBaseEvent();
    message.type = object.type ?? 0;
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseMessage(): Message {
  return { from: "", content: "" };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.from = object.from ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseDrawingPath(): DrawingPath {
  return { pathData: "", stroke: "", strokeWidth: 0, strokeLineCap: "", strokeLineJoin: "" };
}

export const DrawingPath: MessageFns<DrawingPath> = {
  encode(message: DrawingPath, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pathData !== "") {
      writer.uint32(10).string(message.pathData);
    }
    if (message.stroke !== "") {
      writer.uint32(18).string(message.stroke);
    }
    if (message.strokeWidth !== 0) {
      writer.uint32(24).int32(message.strokeWidth);
    }
    if (message.strokeLineCap !== "") {
      writer.uint32(34).string(message.strokeLineCap);
    }
    if (message.strokeLineJoin !== "") {
      writer.uint32(42).string(message.strokeLineJoin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DrawingPath {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDrawingPath();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pathData = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stroke = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.strokeWidth = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.strokeLineCap = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.strokeLineJoin = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DrawingPath {
    return {
      pathData: isSet(object.pathData) ? globalThis.String(object.pathData) : "",
      stroke: isSet(object.stroke) ? globalThis.String(object.stroke) : "",
      strokeWidth: isSet(object.strokeWidth) ? globalThis.Number(object.strokeWidth) : 0,
      strokeLineCap: isSet(object.strokeLineCap) ? globalThis.String(object.strokeLineCap) : "",
      strokeLineJoin: isSet(object.strokeLineJoin) ? globalThis.String(object.strokeLineJoin) : "",
    };
  },

  toJSON(message: DrawingPath): unknown {
    const obj: any = {};
    if (message.pathData !== "") {
      obj.pathData = message.pathData;
    }
    if (message.stroke !== "") {
      obj.stroke = message.stroke;
    }
    if (message.strokeWidth !== 0) {
      obj.strokeWidth = Math.round(message.strokeWidth);
    }
    if (message.strokeLineCap !== "") {
      obj.strokeLineCap = message.strokeLineCap;
    }
    if (message.strokeLineJoin !== "") {
      obj.strokeLineJoin = message.strokeLineJoin;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DrawingPath>, I>>(base?: I): DrawingPath {
    return DrawingPath.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DrawingPath>, I>>(object: I): DrawingPath {
    const message = createBaseDrawingPath();
    message.pathData = object.pathData ?? "";
    message.stroke = object.stroke ?? "";
    message.strokeWidth = object.strokeWidth ?? 0;
    message.strokeLineCap = object.strokeLineCap ?? "";
    message.strokeLineJoin = object.strokeLineJoin ?? "";
    return message;
  },
};

function createBaseClearCanvas(): ClearCanvas {
  return { clear: false };
}

export const ClearCanvas: MessageFns<ClearCanvas> = {
  encode(message: ClearCanvas, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clear !== false) {
      writer.uint32(8).bool(message.clear);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearCanvas {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearCanvas();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.clear = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClearCanvas {
    return { clear: isSet(object.clear) ? globalThis.Boolean(object.clear) : false };
  },

  toJSON(message: ClearCanvas): unknown {
    const obj: any = {};
    if (message.clear !== false) {
      obj.clear = message.clear;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClearCanvas>, I>>(base?: I): ClearCanvas {
    return ClearCanvas.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClearCanvas>, I>>(object: I): ClearCanvas {
    const message = createBaseClearCanvas();
    message.clear = object.clear ?? false;
    return message;
  },
};

function createBaseWordChoice(): WordChoice {
  return { wordIndex: 0 };
}

export const WordChoice: MessageFns<WordChoice> = {
  encode(message: WordChoice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.wordIndex !== 0) {
      writer.uint32(8).int32(message.wordIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WordChoice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWordChoice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.wordIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WordChoice {
    return { wordIndex: isSet(object.wordIndex) ? globalThis.Number(object.wordIndex) : 0 };
  },

  toJSON(message: WordChoice): unknown {
    const obj: any = {};
    if (message.wordIndex !== 0) {
      obj.wordIndex = Math.round(message.wordIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WordChoice>, I>>(base?: I): WordChoice {
    return WordChoice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WordChoice>, I>>(object: I): WordChoice {
    const message = createBaseWordChoice();
    message.wordIndex = object.wordIndex ?? 0;
    return message;
  },
};

function createBaseTurnSummary(): TurnSummary {
  return { usernames: [], scores: [] };
}

export const TurnSummary: MessageFns<TurnSummary> = {
  encode(message: TurnSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.usernames) {
      writer.uint32(10).string(v!);
    }
    writer.uint32(18).fork();
    for (const v of message.scores) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TurnSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTurnSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.usernames.push(reader.string());
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.scores.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.scores.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TurnSummary {
    return {
      usernames: globalThis.Array.isArray(object?.usernames)
        ? object.usernames.map((e: any) => globalThis.String(e))
        : [],
      scores: globalThis.Array.isArray(object?.scores) ? object.scores.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: TurnSummary): unknown {
    const obj: any = {};
    if (message.usernames?.length) {
      obj.usernames = message.usernames;
    }
    if (message.scores?.length) {
      obj.scores = message.scores.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TurnSummary>, I>>(base?: I): TurnSummary {
    return TurnSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TurnSummary>, I>>(object: I): TurnSummary {
    const message = createBaseTurnSummary();
    message.usernames = object.usernames?.map((e) => e) || [];
    message.scores = object.scores?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
